config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "boards#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :boards, only: [:index]

  resources :users do
    resources :boards, only: %i[new create]
  end
  resources :boards, only: %i[index show] do
    resources :reviews, only: %i[new create]
    resources :bookings, only: %i[create]
  end
  namespace :admin do
    resources :bookings, only: %i[index show] do
      collection do
        get :rents
      end
    end
    resources :boards, only: %i[index edit update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  BOARDTYPES = %w[shortboard fish longboard]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews

  validates :name, :price, presence: true
  validates :board_type, inclusion: { in: BOARDTYPES }

  has_many_attached :photos

  def calcul_average
    review_nb = self.reviews.count
    reviews_sum = self.reviews.sum(:rating)
    average = reviews_sum.fdiv(review_nb).round(1)
    self.average_rating = average
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :date_start, :date_end, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [0, 1, 2, 3, 4, 5]
  belongs_to :board

  validates :comment, :rating, presence: true
  validates :rating, inclusion: { in: RATINGS }

  after_create :calculate_board_rating

  def calculate_board_rating
    self.board.calcul_average
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  # my bookings -> la ou booking.board.user_id == current_user.id
  has_many :rents, through: :boards, source: :bookings
  # bookings -> bookings ou user_id == current_user.id
  has_many :bookings, dependent: :destroy
  validates :first_name, :last_name, :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  def index
    @boards = current_user.boards
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to admin_boards_path
    else
      render :edit
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy
    redirect_to admin_boards_path, status: :see_other
  end

  private

  def board_params
    params.require(:board).permit(:name, :description, :board_type, :price, :photos)
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  def index
    # Find all the boards owned by the current user
    # Initialize an empty array to store all bookings
    @review = Review.new
    @bookings = current_user.bookings.order(created_at: :desc)
  end
    # Loop through each board and find its bookings
    # @boards.each do |board|
    #   # Find the bookings associated with this board
    #   board_bookings = board.bookings
    #   @bookings.concat(board_bookings) if board_bookings.any?
    # end

  def rents
    @bookings = current_user.rents
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :location, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :location, :phone_number, :photo])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_user_id, only: %i[new create]
  before_action :authenticate_user!
  def index
    @boards = Board.all.order(updated_at: :desc)
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR description ILIKE :query OR board_type ILIKE :query"
      @boards = @boards.where(sql_subquery, query: "%#{params[:query]}%")
    end
    @users = User.joins(:boards).distinct
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: user}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @board = Board.find(params[:id])
    @booking = Booking.new
    @board.calcul_average
    @markers = [
      {
        lat: @board.user.latitude,
        lng: @board.user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: @board.user}),
        marker_html: render_to_string(partial: "marker")
      }
    ]
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = @user
    if @board.save
      redirect_to boards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_user_id
    @user = User.find(params[:user_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def board_params
    params.require(:board).permit(:name, :description, :board_type, :price, :user_id, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @board = Board.find(params[:board_id])
    @booking.user = current_user
    @booking.board = @board
    if @booking.save
      redirect_to admin_bookings_path
    else
      render "boards/show", status: :unprocessable_entity
    end
  end

  # def destroy
  #   @booking = booking.find(params[:id])
  #   @booking.destroy
  #   redirect_to board_path(@booking.board), status: :see_other
  # end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end, :board_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def new
  #   @review = Review.new
  #   @board = Board.find(params[:board_id])
  #   raise
  # end
  

  def create
    @review = Review.new(review_params)
    @board = Board.find(params[:board_id])
    @review.board = @board
    if @review.save
      redirect_to board_path(@board)
    else
      render :new, status: :unprocessable_entity
    end
    @board.calcul_average
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/boards/edit.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= simple_form_for [@user, @board], html: { class: 'custom-form' }, url: admin_board_path, method: :patch do |f| %>
        <h1 class="text-center mb-4 title">Modifie ta planche</h1>
        <%= f.input :name, label: 'Nom de la planche' %>
        <%= f.input :description, label: 'Description', input_html: { rows: 4 } %>
        <%= f.input :board_type, as: :select, collection: Board::BOARDTYPES, label: 'Type de planche' %>
        <%= f.input :price, label: 'Prix' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: 'Photos' %>
        <%= f.submit "Change ta planche", class: "btn btn-primary mt-3"%>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/boards/index.html.erb
<div class="container">
<h2 class="title my-4" style='text-align: center'>Mes planches</h2>
<ul>
 <div class="cards">
        <% @boards.each do |board| %>

          <div class="card-white">
            <div class="card-img">
              <% if board.photos.attached? %>
              <%= cl_image_tag board.photos.first.key, height: 200, width: 150, crop: :fill %>
              <% else  %>
              <img src="https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-planche-de-surf-sport-et-lifestyle--R96912_PM2_Front%20view.jpg" width="150" height="200" alt="">
              <% end %>
            </div>
            <div class="content">
              <div class="name">
               <h6><strong><%= board.name.upcase %></strong></h6>
              </div>
              <div class="category">
               <p> <strong>Categorie :</strong> <%= board.board_type %></p>
              </div>
              <div class="price_rating">
                <div class="rating">
                  <%= render "shared/star_rating", board: board %>
                </div>

                <p class="price"> <strong><%= board.price %> </strong><i class="fa-solid fa-euro-sign" style="color: #8197f8;"></i></p>
               </div>

          <div class="d-flex  ps-2 justify-content-between mt-2">

            <%= link_to "Supprimer", admin_board_path(board), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-warning" %>
             <%= link_to "Modifier", edit_admin_board_path(board), class: "btn btn-primary" %>
          </div>
          </div>
        </div>
        <% end %>

  </ul>


</div>

app/views/admin/bookings/index.html.erb
<div class="container">
  <h2 class="text-center my-4 title">Mes réservations</h2>


  <div class="row ">
    <div class="col-8">
      <% @bookings.each do |booking| %>
        <div class="mb-4">
          <div class="card booking-card">
            <div class="card-body">
              <h4 class="card-title"> <%= link_to booking.board.name.upcase, board_path(booking.board) %></h4>
              <p class="card-text">
              Localisée à <%= booking.board.user.location %>
              </p>
              <p class="card-text">
              Planche louée pendant <%= (booking.date_end - booking.date_start).to_i %> jours auprès de <%= booking.board.user.first_name.upcase %>.
            </p>

            </div>
            <div class="card-footer text-muted">
              <div class="price-icon">
                <i class="fas fa-coins"></i>
                <%= (booking.board.price * (booking.date_end - booking.date_start)) %> euros
              </div>
              <div>
                <!-- Button trigger modal -->
                  <button class="btn btn-primary" type="button"  data-bs-toggle="modal" data-bs-target="#<%= dom_id(booking.board) %>">
                    Laisser un avis
                  </button>

                  <!-- Modal -->
                  <div class="modal fade" id="<%= dom_id(booking.board) %>" tabindex="-1" aria-labelledby="<%= dom_id(booking.board) %>Label" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Laisser mon avis</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <div class="col-md-12">
                            <%= simple_form_for [booking.board, @review], html: { class: 'custom-form' } do |f| %>
                              <h1 class="text-center mb-4 title">Ajoute ton avis sur la planche</h1>
                              <%= f.input :comment, label: 'Commentaire' %>
                              <%= f.input :rating, as: :select, collection: Review::RATINGS, label: 'Note sur 5', input_html: {data: {controller: "star-rating"}} %>
                              <%= f.submit "Valide ton avis", class: "btn btn-primary mt-3" %>
                              <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="date-icon">
                <i class="fas fa-calendar-alt"></i> <%= booking.date_start.strftime('%d/%m/%Y') %> - <%= booking.date_end.strftime('%d/%m/%Y') %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-3">
       <div class="mb-4 sticky-card">
        <div class="card summary-card">
          <div class="card-body ">
            <h5 class="card-title">Récapitulatif</h5>
            <p class="card-text">Nombre de réservations : <%= @bookings.count %></p>
            <p class="card-text">Dépenses total : <%= @bookings.sum { |booking| booking.board.price * (booking.date_end - booking.date_start) } %> euros</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/bookings/rents.html.erb
<div class="container">
  <h2 class="text-center my-4 title">Mes locataires</h2>


  <div class="row ">
    <div class="col-8">
      <% @bookings.each do |booking| %>
        <div class="mb-4">
          <div class="card booking-card">
            <div class="card-body">
              <h4 class="card-title"> <%= link_to booking.board.name.upcase, board_path(booking.board) %></h4>
              <p class="card-text">
              Planche louée pendant <%= (booking.date_end - booking.date_start).to_i %> jours par <%= booking.user.first_name.upcase %>.
            </p>
            </div>
            <div class="card-footer text-muted">
              <div class="price-icon">
                <i class="fas fa-coins"></i>
                <%= (booking.board.price * (booking.date_end - booking.date_start)) %> euros
              </div>
              <div class="date-icon">
                <i class="fas fa-calendar-alt"></i> <%= booking.date_start.strftime('%d/%m/%Y') %> - <%= booking.date_end.strftime('%d/%m/%Y') %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-3">
       <div class="mb-4 sticky-card">
        <div class="card summary-card">
          <div class="card-body ">
            <h5 class="card-title">Récapitulatif</h5>
            <p class="card-text">Nombre de locataires : <%= @bookings.count %></p>
            <p class="card-text">Gain total : <%= @bookings.sum { |booking| booking.board.price * (booking.date_end - booking.date_start) } %> euros</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/bookings/show.html.erb
<div class="container-fluid row justify-content-center">
  <h2 style='text-align: center'><%= @booking.board.name.upcase %></h2>

    <div class="card-white">
      <div class="card-img">
        <% if @booking.board.photos.attached? %>
        <%= cl_image_tag @booking.board.photos.first.key, height: 200, width: 150, crop: :fill %>
        <% else  %>
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png" width="150" height="200" alt="">
        <% end %>
      </div>
        <div class="content">
        <h6><strong><%= @booking.board.name %></strong></h6>
        <p> <strong>Categorie :</strong> <%= @booking.board.board_type %></p>
        <p> Planche louée du <%= @booking.date_start%> au <%= @booking.date_end %></p>
        <p> <strong><%= (@booking.board.price * (@booking.date_end - @booking.date_start)).round(2) %> </strong> euros</p>
      </div>
      <button class="btn btn-surf"><%= link_to 'Retour sur mes réservations', admin_bookings_path(current_user) %>
      </button>
    </div>
</div>

app/views/boards/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= simple_form_for [board, booking], html: { class: 'custom-form' } do |f| %>
      <h1 class="text-center mb-4">Réserve ta planche de surf</h1>
      <%= f.input :date_start, label: 'Date de début', as: :string, input_html: { data: { controller: "datepicker", reservation_modal_target: 'inputStartDate' } } %>
      <%= f.input :date_end, label: 'Date de fin', as: :string, input_html: { data: { controller: "datepicker", reservation_modal_target: 'inputEndDate'  } } %>
      <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#bookingConfirmation" data-action='click->reservation-modal#displayContent'>
        Valider
      </button>
      <div class="modal fade" id="bookingConfirmation" tabindex="-1" role="dialog" aria-labelledby="reservationModalLabel" aria-hidden="true" >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="reservationModalLabel">Récapitulatif de la réservation</h5>
              </button>
            </div>
            <div class="modal-body modal-padding">
              <p>Vous êtes sur le point de valider la location suivante :</p>
              <div class="">
              <ul>

                <div class="d-flex flex-row justify-content-between">
                  <div>
                    <li>Date de début :
                  </div>
                  <div>
                    <strong>
                    <span data-reservation-modal-target="startDate"></span> </strong></li>
                  </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                  <div>
                    <li>Date de fin :
                  </div>
                  <div>
                  <strong>
                    <span data-reservation-modal-target="endDate"></span> </strong></li>
                  </div>
                </div>
                <div class="d-flex flex-row justify-content-between">
                  <div>
                     <li>Durée de la location :
                    </div>
                    <div>
                      <strong>
                        <span data-reservation-modal-target="totalDays"></span> jours </strong></li>
                    </div>
                  </div>
                <div class="d-flex flex-row justify-content-between">
                  <div>
                    <li>Total de votre réservation :
                  </div>
                  <div>
                    <strong>
                     <span data-reservation-modal-target="totalPrice"></span>€ </strong></li>
                  </div>
                </div>
              </ul>
              </div>
            </div>
            <div class="modal-footer justify-content-between">
              <%= link_to "Annuler", board_path(board), class: "btn btn-warning btn-cancel mt-3", data: { dismiss: "modal" } %>
              <%= f.button :submit, "Valide ta réservation", class: "btn btn-primary mt-3", data: { toggle: "modal", target: "reservation-modal.modal" } %>
            </div>
          </div>
        </div>
      </div>

      <%#= f.button :submit, "Valide ta réservation", class: "btn btn-primary mt-3", data: { toggle: "modal", target: "reservation-modal.modal" } %>
    <% end %>
  </div>
</div>

app/views/boards/_info_window.html.erb
  <% user.boards.each do |board| %>
    <div class="my-3 card-window d-flex flex-column ">
      <%= link_to board_path(board) do %>
        <div class=" d-flex flex-column align-items-center">
          <% if board.photos.attached? %>
            <%= cl_image_tag board.photos.first.key, height: 100, width: 100, crop: :fill %>
            <% else  %>
            <img src="https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-planche-de-surf-sport-et-lifestyle--R96912_PM2_Front%20view.jpg" width="50" height="100" alt="">
          <% end %>
        </div>
        <h6 class="pt-2"><%= board.name %></h6>
      <% end %>
    </div>
  <% end %>

app/views/boards/_marker.html.erb
<%= image_tag "logo_marker.png", height: 45, width: 45, alt: "Logo" %>

app/views/boards/index.html.erb
<div class="background">
  <h1 style='text-align: center'>Liste des planches disponibles</h1>
</div>
<div class="container">
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
  <div class="search-bar ">
    <%= form_with url: boards_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Filtre par nom, description ou par type de planche (shortboard, longboard, fish)"
        %>
      <%= submit_tag "Filtrer", name: "", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>
<h5 class="card-text mx-3 my-3"><strong> <%= @boards.count %> </strong>planches sont disponibles actuellement</h5>

<div class="row">
  <div class="col-8">
    <%= render 'shared/index' %>
  </div>
<div class="col-4">
  <div class="mapbox sticky-card"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="forms col-md-6">
      <%= simple_form_for [@user, @board], html: { class: 'custom-form' } do |f| %>
        <h1 class="text-center mb-4 title">Ajoute une planche</h1>
        <%= f.input :name, label: 'Nom de la planche' %>
        <%= f.input :description, label: 'Description', input_html: { rows: 4 } %>
        <%= f.input :board_type,
                    as: :select,
                    collection: Board::BOARDTYPES,
                    label: 'Type de planche',
                    wrapper_html: { class: "test"},
                    input_html: {data: {controller: "tom-select", tom_select_options_value: {tags: true}}} %>
        <%= f.input :price, label: 'Prix' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: 'Photos', class:'picture-select'%>


        <%= f.submit "Valide ta planche", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurfAi</title>
    <%= favicon_link_tag "logo-title.png", rel: "icon", type: "image/png" %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
@import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@10..48,200;10..48,300;10..48,400;10..48,500;10..48,600;10..48,700;10..48,800&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
</style>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="main-cont">
      <%= yield %>
    </div>

    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= simple_form_for [@board, @review], html: { class: 'custom-form' } do |f| %>
        <h1 class="text-center mb-4 title">Ajoute ton avis sur la planche</h1>
        <%= f.input :comment, label: 'Commentaire' %>
        <%= f.input :rating, as: :select, collection: Review::RATINGS, label: 'Note sur 5', input_html: {data: {controller: "star-rating"}} %>
        <%= f.submit "Valide ton avis", class: "btn btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-expand-sm">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Ce site a été réalisé <i class="fas fa-heart"></i> par <strong>3 légendes</strong>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky">
  <div class="container-fluid">
    <%= link_to boards_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in?  %>
          <li class="nav-item active">
            <%= link_to "Paillote", boards_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ajouter une planche", new_user_board_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.present? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "#{current_user.first_name}" %>
            <% else %>
                <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" alt="photo wagon">
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes planches", admin_boards_path, class: "dropdown-item" %>
              <%= link_to "Mes reservations", admin_bookings_path, class: "dropdown-item" %>
              <%= link_to "Mes locataires", rents_admin_bookings_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else  %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>